apiVersion: apps/v1
kind: Deployment
metadata:
  name: mygps
  namespace: mygps
  labels:
    app: mygps
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mygps
  template:
    metadata:
      labels:
        app: mygps
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: mygps
        image: fkam18/mygps
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux

